spring.application.name=EmployeeAddress
server.port = 8082

# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/empaddress

# Username & Password
spring.datasource.username=root
spring.datasource.password=anwesha123

# Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate (JPA)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.customCssUrl=/swagger-dark.css
springdoc.swagger-ui.customJs=/swagger-dark.js
